-- Baseline schema matching the current JPA entities (Hibernate 7 / PostgreSQL).
-- Generated to agree with spring.jpa.hibernate.ddl-auto=validate.

create table app_user (
    date_of_birth date,
    id bigint generated by default as identity,
    email varchar(255) not null unique,
    gender varchar(255) check ((gender in ('MALE','FEMALE','OTHER'))),
    name varchar(255),
    password varchar(255) not null,
    primary key (id)
);

create table user_roles (
    user_id bigint not null,
    roles varchar(255) check ((roles in ('GUEST','HOTEL_MANAGER','ADMIN'))),
    unique (user_id, roles)
);

create table hotel (
    active boolean not null,
    average_rating float(53) not null,
    review_count integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    owner_id bigint not null,
    updated_at timestamp(6) not null,
    address varchar(255),
    city varchar(255),
    email varchar(255),
    location varchar(255),
    name varchar(255) not null,
    phone_number varchar(255),
    amenities TEXT[],
    photos TEXT[],
    primary key (id)
);

create table room (
    base_price numeric(10,2) not null,
    capacity integer not null,
    total_count integer not null,
    created_at timestamp(6) not null,
    hotel_id bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    type varchar(255) not null,
    amenities TEXT[],
    photos TEXT[],
    primary key (id)
);

create table inventory (
    booked_count INTEGER DEFAULT 0 not null,
    closed boolean not null,
    date date not null,
    price numeric(10,2) not null,
    reserved_count INTEGER DEFAULT 0 not null,
    surge_factor numeric(5,2) not null,
    total_count integer not null,
    created_at timestamp(6) not null,
    hotel_id bigint not null,
    id bigint generated by default as identity,
    room_id bigint not null,
    updated_at timestamp(6) not null,
    city varchar(255) not null,
    primary key (id),
    constraint unique_hotel_root_date unique (hotel_id, room_id, date)
);

create table guest (
    age integer,
    id bigint generated by default as identity,
    user_id bigint,
    gender varchar(255) check ((gender in ('MALE','FEMALE','OTHER'))),
    name varchar(255) not null,
    primary key (id)
);

create table booking (
    amount numeric(10,2) not null,
    check_in_date date not null,
    check_out_date date not null,
    expiry_warning_sent boolean not null,
    refund_amount numeric(10,2),
    rooms_count integer not null,
    created_at timestamp(6) not null,
    hold_expires_at timestamp(6),
    hotel_id bigint not null,
    id bigint generated by default as identity,
    room_id bigint not null,
    updated_at timestamp(6) not null,
    user_id bigint not null,
    booking_status varchar(255) not null check ((booking_status in ('RESERVED','GUEST_ADDED','PAYMENT_PENDING','CONFIRMED','CANCELLED','EXPIRED','REFUNDED'))),
    idempotency_fingerprint varchar(255),
    idempotency_key varchar(255) unique,
    payment_session_id varchar(255),
    primary key (id)
);

create table booking_guest (
    booking_id bigint not null,
    guest_id bigint not null,
    primary key (booking_id, guest_id)
);

create table hotel_min_price (
    date date not null,
    price numeric(10,2) not null,
    created_at timestamp(6) not null,
    hotel_id bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint unique_hotel_min_price_date unique (hotel_id, date)
);

create table review (
    rating integer not null,
    booking_id bigint not null unique,
    created_at timestamp(6) not null,
    hotel_id bigint not null,
    id bigint generated by default as identity,
    user_id bigint not null,
    comment varchar(2000),
    primary key (id)
);

create table wishlist_item (
    created_at timestamp(6) not null,
    hotel_id bigint not null,
    id bigint generated by default as identity,
    user_id bigint not null,
    primary key (id),
    unique (user_id, hotel_id)
);

create table processed_stripe_event (
    processed_at timestamp(6) not null,
    event_id varchar(255) not null,
    event_type varchar(255) not null,
    primary key (event_id)
);

create index idx_booking_payment_session on booking (payment_session_id);
create index idx_booking_status_hold on booking (booking_status, hold_expires_at);
create index idx_booking_user on booking (user_id);
create index idx_booking_hotel on booking (hotel_id);
create index idx_hotel_owner on hotel (owner_id);
create index idx_hotel_city_active on hotel (city, active);
create index idx_hotel_min_price_date on hotel_min_price (date, hotel_id);
create index idx_inventory_city_date on inventory (city, date);
create index idx_inventory_room_date on inventory (room_id, date);
create index idx_review_hotel on review (hotel_id);
create index idx_review_user on review (user_id);
create index idx_room_hotel on room (hotel_id);
create index idx_wishlist_hotel on wishlist_item (hotel_id);

alter table booking add constraint FKhacdq9bfa3r9xdimovsnonbyi foreign key (hotel_id) references hotel;
alter table booking add constraint FKq83pan5xy2a6rn0qsl9bckqai foreign key (room_id) references room;
alter table booking add constraint FKn7phgawjwo673xgim9d2cvfe1 foreign key (user_id) references app_user;
alter table booking_guest add constraint FKbidkmu7pdnm82qpo2r3n699yd foreign key (guest_id) references guest;
alter table booking_guest add constraint FKngrkuwlsaqjwe4mycjdvhuwtk foreign key (booking_id) references booking;
alter table guest add constraint FKdg6lwhvpl89f1yt2i40pbfiiy foreign key (user_id) references app_user;
alter table hotel add constraint FKdihygcg12c598wu6e18l5sd0t foreign key (owner_id) references app_user;
alter table hotel_min_price add constraint FKne8dgpjep57pvqfiv4g1c7nch foreign key (hotel_id) references hotel;
alter table inventory add constraint FK81iasgjh573hbsoluoj670bkj foreign key (hotel_id) references hotel;
alter table inventory add constraint FKkkm00xm4as7hupix7tlg0q3of foreign key (room_id) references room;
alter table review add constraint FKk4xawqohtguy5yx5nnpba6yf3 foreign key (booking_id) references booking;
alter table review add constraint FKi0ly7ivbh8ijdgoi7cwtuoavt foreign key (hotel_id) references hotel;
alter table review add constraint FKc7y0l3wac4n2ewm6a2uecd54c foreign key (user_id) references app_user;
alter table room add constraint FKdosq3ww4h9m2osim6o0lugng8 foreign key (hotel_id) references hotel;
alter table user_roles add constraint FK6fql8djp64yp4q9b3qeyhr82b foreign key (user_id) references app_user;
alter table wishlist_item add constraint FKa8piaqcvunum5mxcodrl6i5w0 foreign key (hotel_id) references hotel;
alter table wishlist_item add constraint FK2ljprlxpxkxeb5so8dsvi4aih foreign key (user_id) references app_user;
